[package]
name = "client-util"
version = "0.1.0"
edition = "2021"

[dependencies]
# tokio = { version = "1.18.2", features = ["full"] }
gdnative = "0.10"
bluetooth-serial-port = { path = "../../../bluetooth-serial-port"}
hex = "0.4.3"

common = { path = "../common" }


[lib]
crate-type = ["cdylib"]