[package]
name = "stm32-rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdnative = "0.9"
probe-rs ="0.11.0"
probe-rs-rtt = "0.11.0"

[lib]
crate-type = ["cdylib"]